config/routes.rb
Rails.application.routes.draw do

  
  
  get 'contacts/index'

  resources :concerts
  devise_for :admins

  get 'BookingVE', to: 'home#BookingVE', as: 'BookingVE'

  
  get 'admin', to: 'admin#index'
  get 'home', to: 'home#index'
  get 'privacy', to: 'privacy#index'
  get 'reviews', to: 'review#index'
  get 'songs', to: 'songs#index'
  get 'venues', to: 'venues#index'
  get 'emails', to: 'home#index'
  get 'media', to: 'uploads#index'
  # get 'about', to: 'abouts#index'
  get 'contact', to: 'contacts#index'
  resources :contact, only: [:index, :new, :create]

#calendar
# get '/redirect', to: 'example#redirect', as: 'redirect'
# get '/callback', to: 'example#callback', as: 'callback'
  get 'event/:date/:location/:type/:length/:contact_id/:fname/:lname/:email/:phone/:message', to: 'events#new', as: 'new_event_path'

  # get 'new/:amount/:eventdate/:eventlocation/:deposit/:description/:fname/:lname', to: 'charges#new', as: 'new_charge_path'
  namespace :stripe do
    resources :charges, only: :create
  end  
  
  resources :musicians

  resources :events
  resources :customers
  resources :emails

  resources :abouts
  resources :venues
  # resources :uploads
  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/concert.rb
class Concert< ActiveRecord::Base
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  define_model_callbacks :deliver
  include MailForm::Delivery

  # append :remote_ip, :user_agent, :session
  
  attribute :fname, :validate => true
  attribute :lname
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone
  attribute :eventdate, :validate => true
  attribute :eventlocation
  attribute :type
  attribute :heardby
  attribute :length
  attribute :message, :validate => true
  attribute :nickname, :captcha  => true
  attribute :customer_id
  attribute :event_id

  def headers
    {
      :subject => "New Message - Velveteen Ensemble",
      :to => "marcel@velveteenensemble.com", 
      :from =>  %("#{fname}" <#{email}>)
    }
  end
end

app/models/email.rb
class Email < ApplicationRecord
	attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :nickname, :captcha  => true

end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
	 mount_uploader :name, ImageUploader
end

app/models/venue.rb
class Venue < ApplicationRecord

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/admin/_login.html.erb
<div class="background row login">
			<div class="col-md-12">
				<h2>Admin Login</h2>
			</div>

			<div class="col-md-12">
				<%= form_for(:admin, :url => session_path(:admin)) do |f| %>
				  <div class="field">
				    <%= f.label :email %><br />
				    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
				  </div>

				  <div class="field">
				    <%= f.label :password %><br />
				    <%= f.password_field :password, autocomplete: "off" %>
				  </div>

				  <div class="field">
				    <%= f.check_box :remember_me %>
				    <%= f.label :remember_me %>
				  </div>

				  <div class="actions">
				    <%= f.submit "Log in" %>
				  </div>
				  <%= link_to "Forgot your password?", new_password_path(:admin) %>
				<% end %>


				<% if admin_signed_in? %>
					<h1>Emails</h1>

					<table>
					  <thead>
					    <tr>
					      <th>Name</th>
					      <th>Email</th>
					      <th colspan="3"></th>
					    </tr>
					  </thead>

					  <tbody>
					    <% @emails.each do |email| %>
					      <tr>
					        <td><%= email.name %></td>
					        <td><%= email.email %></td>
					        <td><%= link_to 'Edit', edit_email_path(email) %></td>
					        <td><%= link_to 'Destroy', email, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					      </tr>
					    <% end %>
					  </tbody>
					</table>

					<br>

					<%= link_to 'New Email', new_email_path %>

				<% end %>
			</div>
		</div>
	<% else %>

app/views/admin/index.html.erb
<div class="container-fluid height admin">
	<% unless admin_signed_in? %>
			<%= render '/admin/login' %>
	<% end %>

	<% if admin_signed_in? %>
		<div class="links col-md-12 no-gutters">
			<ul class="no-gutters">
				<li class="col-md-4 col-sm-4 col-xs-4 no-gutters color hover" id="link1">Event Management</li>
				<li class="col-md-4 col-sm-4 col-xs-4 no-gutters color" id="link2">Calendar</li>
				<li class="col-md-4 col-sm-4 col-xs-4 no-gutters color" id="link3">Email List</li>
			</ul>
		</div>



		<!------- Email and Event Management page ------->



		<div id="admin1" class=" col-md-12 hidepages">
			<div class="row heading">
				<div class="col-md-4"></div>
				<div class="col-md-4">
					<h4>Upcoming Events</h4>
				</div>
				<div class="col-md-4 left">

				<!-- 	<#%= link_to new_event_path, :date =>' require?', :location => ' require?', :type => ' require?', :type => ' require?', :length => ' require?' do %>
				 		<button>New Event</button>
				 	<#% end %>  -->

				</div>
				
			</div>
			<div class="no-gutters events">
				<div class="background row">
				 	<p>Carnegie Hall</p>
				 	<p>Dec. 22nd</p>
				 	<%= link_to edit_event_path(@events) do %> 
				 		<button>Edit Event</button>
				 	<% end %> 
				</div>
				<% @events.each do |event| %>
					<div class="background row">
						<p><%= event.title%></p>
						<p><%= event.date.to_time.strftime('%a %b %d, %Y')%></p>
						<%= link_to event_path(event) do %> 
						<button>Show</button>
						<% end %>|
						<%= link_to edit_event_path(event) do %> 
				 			<button>Edit</button>
				 		<% end %> 
					</div>
				<% end %>
				<%= image_tag image_url('https://s3.amazonaws.com/velveteenensemble/nofillarrow.png') %>
			</div>
			<hr>
		<!-- 	<div class="row heading2">
				<h4>Clients</h4>
			</div> -->
<!-- 			<div class="no-gutters customers">
				
				<div class="background row">
				 	<p>Marcel Krasner</p>
				 	<p>marcelkrasner@gmail.com</p>
				 		<#%= link_to customer_path(@customers) do %> 
				 		<button>Go To Client Page</button>
				 	<#% end %> 
				</div>
				<#% @customers.each do |customer| %>
				 	<div class="background row">
				 		<p><#%= customer.fname%></p>
				 		<p><#%= customer.email%></p>
				 		<#%= link_to customer_path(customer) do %> 
				 		<button>Edit Event</button>
				 		<#% end %> 
				 	</div>
				<#% end %>

				<#%= image_tag image_url('https://s3.amazonaws.com/velveteenensemble/nofillarrow.png') %>
			</div> -->
			<!-- <hr> -->
			<div class="col-md-12 no-gutters contacts">
				<div class="row">
					<h4>Emails</h4>
				</div>
				 <% @contacts.order('created_at DESC').each do |contact| %>
				 	<div class="background">
				 		<div class="row">
				 			<div class="col-md-6">
				 				<p><b><%= contact.fname %>   &nbsp&nbsp<%= contact.lname %></b></p>
				 			</div>
				 			<div class="col-md-6">
				 				<p class=" dates row"><b> Event Date: <%= contact.eventdate.strftime("%B %d, %Y") %></b></p>
				 				<p class="emaildate dates row">Email Sent: <%= contact.created_at.strftime("%B %d, %Y")%></p>
				 				
				 			</div>
				 		</div>
				 		<p class="message"><%= contact.message %></p>
				 		<br>
				 		<div class="row no-gutters">
					 		<div class="col-md-4"></div>
					 		<div class="col-md-4">

						 	<%= link_to new_event_path(date: contact.eventdate, location: contact.eventlocation, event_type: contact.event_type, other_type: contact.other_type, length: contact.length, contact_id: contact.id, fname: contact.fname, lname: contact.lname, email: contact.email, phone: contact.phone, message: contact.message) do %>
						 			<button>Add as an Event</button>
						 		<% end %>


						 	<!-- 	<a href='<#%= new_event_path(date: event.eventdate, location: event.eventlocation, type: event.type, type: event.type, length: event.length) %>'>
  								<h2>Add event</h2>
								</a> -->



					 		</div>
					 		<div class="col-md-4 deletecontact">
	       			 	<!-- <#%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' } %> -->

	       			 	<!-- <#%= form_for(contact, edit_path(contact), remote: true) do |f| %> -->
							    <!-- <div><#%= f.hidden_field :contact_id %></div> -->
							    <!-- <div><#%= f.hidden_field :hidden, :value => true %></div> -->
							    <!-- <#%= f.submit "Remove", class: "btn btn-large btn-primary" %> -->
							<!-- <#% end %> -->

	     			 	</div>




     			 	</div>
				 		
				 		<br>
				 		
				 		
				 		<br>
				 	</div>
				 <% end %>
			</div>

		</div>



		<!------- Calendar page ------->



		<div id="admin2" class="col-md-12 no-gutters hidepages">
			<div class="row no-gutters calendar">
				<!-- <iframe src="https://calendar.google.com/calendar/embed?title=Velveteen%20Ensemble&amp;height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=velveteenensemble.com_mh8rm5olauqbct9squ4v6uka30%40group.calendar.google.com&amp;color=%2329527A&amp;ctz=America%2FNew_York" style="border-width:0" height="600px" frameborder="0" scrolling="no"> -->
				<!-- </iframe> -->
			</div>
		</div>



		<!------- Email List page ------->



		<div id="admin3" class="col-md-12 hidepages">
			<div class="background row emaillist">
				<table>
					<thead>
						<tr>
							<th class="col-xs-12" colspan="3"><h3>Mailing list</h3></th>
						</tr>
					  <tr>
					    <th class="emailcol">Email</th>
					    <!-- <th class="hide600">Name</th>  -->
					    <!-- <th class="linkcol">Links</th> -->
				  	</tr>
				  </thead>
				  <tbody>
				  	<% @singlelist.each do |list| %>
							<tr>
								<td class="emailcol"><%= list %></td>
								<!-- <td class="hide600"><#%= event.fname%></td> -->
								<!-- <td class="linkcol">
	            			<#%= link_to 'Edit', edit_email_path(email) %>
	            			<div class="vertical"></div>
	            			<#%= link_to 'Delete', @email = email, :method => :delete, :confirm => "Are you sure?" %>
	       		 			</td> -->
							</tr>
						<% end %>	
					</tbody>
				</table>
			</div>
			<div class="background row copyemails">

				<p id="copyme">
					<%= @singlecopy %>
				</p>

				<button class="clipboard-btn" data-clipboard-action="copy" data-clipboard-target="#copyme">
				   Copy email list to clipboard
				</button>
			</div>
		</div>
	<% end %>
</div>

app/views/layouts/_email.html.erb
 <!-- <#% if @first_visit %> -->
<% if @homepage %>
  <div class="new-visitor-show background" id="email">
	  	<div id="close">X</div>
	  	<div class=" no-gutters ">
	  		<!-- <div class="row"> -->
	  			<h5>Enter your email and receive <br>15% off any order if you book with us!</h5>
	  		<!-- </div> -->
	  		<div class="row">
	  			<%= render '/emails/form', email: @email %>
	  		</div>
			</div>
	</div>
	<% end %>
<!-- <#% end %> -->

app/views/layouts/_footer.html.erb
<% unless @landing %>

	<div class="container-fluid no-gutters" id="footer">
		<div class="col-md-4 col-sm-4 col-xs-4">
			<div class="row">
				<p>917.733.4650</p>
			</div>
			<div class="row">
				<p>marcel@velveteenensemble.com</p>
			</div>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-4">
			<div class="row">
				<h5>Copyright © Velveteen Ensemble</h5>
			</div>
			<div class="row">
				<p><%= link_to "Privacy Policy", "/privacy"%></p>
			</div>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-4">
			<div class="row">
				<p>Website By</p>
			</div>
			<div class="row">
				<p><%= link_to "Hans Palacios", "https://www.hspalacios.com", :target => "_blank" %></p>
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/_header.html.erb
<% unless @landing %>
	<div class="row no-gutters" >
		<div id="trigger1"></div>
		<div id="header">
			<% if notice %>
			  <p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
			  <p class="alert alert-danger"><%= flash[:error] %><%= alert %></p>
			<% end %>
			<a href="/" id="logo" >
				<%= image_tag image_url('https://d3ffc7oj6uo4uj.cloudfront.net/whlogolines.png'), :id => "logo" %>
			</a>
			<ul>
				<li><a href="/abouts">About</a></li>
				<li><a href="/venues">Venues</a></li>
				<li><a href="/media">Media</a></li>
				<li><a href="/songs">Songs</a></li>
				<li><a href="/reviews">Reviews</a></li>
				<li><a href="/contact">Contact</a></li>
			</ul>
			 <% if admin_signed_in? %>
			 	<div id="adminlinks">
			 		<a href="/admin">Admin Page</a>
	     		<%= link_to "Log out", destroy_admin_session_path, method: :delete, :id => "logout" %>
	     	</div>
	     <% end %>
			<div class="dropdown">
				<%= image_tag image_url("https://d3ffc7oj6uo4uj.cloudfront.net/hamburgermenu.png") %>
				<div class="dropdown-content">
				  <a href="/abouts">About</a>
				  <a href="/venues">Venues</a>
				  <a href="/media">Media</a>
					<a href="/songs">Songs</a>
					<a href="/reviews">Reviews</a>
					<a href="/contact">Contact</a>
					<% if admin_signed_in? %>
						<a href="/admin">Admin Page</a>
						<%= link_to "Log out", destroy_admin_session_path, method: :delete, :id => "logout" %>
				<% end %>
				</div>
			</div>
		</div>
	</div>
	<style>
		<% if @homepage %>
			#header {
				position: static;
				position: relative;
			}
			.height {
				min-height: calc(100% - 120px);
			}
			@media only screen and (min-width: 992px) {
				#header {
					height: 120px;
					padding: 20px;
				}
				#header #logo {
					height: 70px;
					margin-right: 5%;
				}
				#header ul {
					top: 40px;
				}
			}
		<% end %>
		<% if admin_signed_in? %>
		#header .alert {
			right: 150px;
		}
			@media only screen and (max-height: 410px) {
				.dropdown-content {
					height: 308px;
					overflow: scroll;
				}
			}
			@media only screen and (max-height: 366px) {
				.dropdown-content {
					height: 264px;
					overflow: scroll;
				}
			}
			<% else %>
			@media only screen and (max-height: 322px) {
				.dropdown-content {
					height: 220px;
					overflow: scroll;
				}
			}
			@media only screen and (max-height: 278px) {
				.dropdown-content {
					height: 176px;
					overflow: scroll;
				}
			}
			@media only screen and (max-height: 234px) {
				.dropdown-content {
					height: 132px;
					overflow: scroll;
				}
			}
			@media only screen and (max-height: 190px) {
				.dropdown-content {
					height: 88px;
					overflow: scroll;
				}
			}
			@media only screen and (max-height: 146px) {
				.dropdown-content {
					height: 44px;
					overflow: scroll;
				}
			}
		<% end %>
	</style>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<title>Velveteen Ensemble - New York Ceremony Music, Concerts/Tours, Weddings</title>
<meta name="Description" content="Velveteen Ensemble is a New York-based group that performs Concerts/Tours, Luxury Weddings, Corporate Functions, Recording Sessions in NYC/Miami/LA/China.">
<meta name="Keywords" content="Velveteen Ensemble, Concerts, Tours, Luxury Weddings, Corporate Functions, Recording Sessions, holiday parties, corporate events, Venues">
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0"/>
    
    <meta name="google-site-verification" content="D7xfVefyJ62-eldnKXyr9b3AvNaBMtGJ3ka_xhzXGxk" />

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap-grid.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.14.2/TweenMax.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js
"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/plugins/animation.gsap.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Tangerine&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-132039324-1"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-132039324-1');
</script>


  </head>

  <body>

    <%= render '/layouts/header' %>
    <!-- <#%= render '/layouts/email' %> -->

    <%= yield %>

    <%= render '/layouts/footer' %>

  </body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <style>

  </style>
  </body>
</html>