config/routes.rb
Rails.application.routes.draw do

  
  
  get 'contacts/index'

  resources :concerts
  devise_for :admins

  get 'BookingVE', to: 'home#BookingVE', as: 'BookingVE'

  
  get 'admin', to: 'admin#index'
  get 'home', to: 'home#index'
  get 'privacy', to: 'privacy#index'
  get 'reviews', to: 'review#index'
  get 'songs', to: 'songs#index'
  get 'venues', to: 'venues#index'
  get 'emails', to: 'home#index'
  get 'media', to: 'uploads#index'
  # get 'about', to: 'abouts#index'
  get 'contact', to: 'contacts#index'
  resources :contact, only: [:index, :new, :create]

#calendar
# get '/redirect', to: 'example#redirect', as: 'redirect'
# get '/callback', to: 'example#callback', as: 'callback'
  get 'event/:date/:location/:type/:length/:contact_id/:fname/:lname/:email/:phone/:message', to: 'events#new', as: 'new_event_path'

  # get 'new/:amount/:eventdate/:eventlocation/:deposit/:description/:fname/:lname', to: 'charges#new', as: 'new_charge_path'
  namespace :stripe do
    resources :charges, only: :create
  end  
  
  resources :musicians

  resources :events
  resources :customers
  resources :emails

  resources :abouts
  resources :venues
  # resources :uploads
  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/concert.rb
class Concert< ActiveRecord::Base
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  define_model_callbacks :deliver
  include MailForm::Delivery

  # append :remote_ip, :user_agent, :session
  
  attribute :fname, :validate => true
  attribute :lname
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone
  attribute :eventdate, :validate => true
  attribute :eventlocation
  attribute :type
  attribute :heardby
  attribute :length
  attribute :message, :validate => true
  attribute :nickname, :captcha  => true
  attribute :customer_id
  attribute :event_id

  def headers
    {
      :subject => "New Message - Velveteen Ensemble",
      :to => "marcel@velveteenensemble.com", 
      :from =>  %("#{fname}" <#{email}>)
    }
  end
end

app/models/email.rb
class Email < ApplicationRecord
	attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :nickname, :captcha  => true

end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
	 mount_uploader :name, ImageUploader
end

app/models/venue.rb
class Venue < ApplicationRecord

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
  	@songs  = Song.all
  end

  def edit
    @song = Song.find(params[:id])
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
  end

  def upload
  	unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
  end

  def new
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
    @song = Song.new
  end

  def show 
  	unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
        @song = Song.find(params[:id])

  end

  # def delete
  # 	unless admin_signed_in? 
  #     flash[:notice] = "You don't have access to that page!"
  #     redirect_to root_path
  #     return
  #   end
  # end
  def create

    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end

    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
      @song = song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
      params.require(:song).permit(:title, :bio, :name)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :song_title %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :song_artist %>
  </div>

  <!-- <hr> -->
 <!--  <b><h5>Only fill out following  if editing or adding a sample song</b></h5>

  <div class="field">
    <#%= form.label :genre %>
    <#%= form.text_field :genre, id: :song_genre %>
  </div> -->

  <!-- div class="field">
    <#%= form.label :file %>
    <#%= form.text_field :file, id: :song_file %>
  </div> -->

 <!--  <div class="field">
    <#%= form.label :play, "Sample" %>
    <#%= form.check_box :play, id: :song_play %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<div class="container-fluid editpage height">
	<div class="background">
			<div class="row">
				<h3>Editing Song</h3>
			</div>
			<div class="row">
				<%= render 'form', song: @song %>
			</div>
			<div class="row">
				<div class="links">
					<%= link_to 'Show', @song %> |
					<%= link_to 'Back', songs_path %>
				</div>
			</div>
	</div>
</div>

app/views/songs/index.html.erb
<head>
	<title>Velveteen Ensemble Song List and Sample Music</title>
	<!-- Facebook Pixel Code -->
	<script>
	!function(f,b,e,v,n,t,s)
	{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
	n.callMethod.apply(n,arguments):n.queue.push(arguments)};
	if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
	n.queue=[];t=b.createElement(e);t.async=!0;
	t.src=v;s=b.getElementsByTagName(e)[0];
	s.parentNode.insertBefore(t,s)}(window,document,'script',
	'https://connect.facebook.net/en_US/fbevents.js');
	 fbq('init', '433933810863059'); 
	fbq('track', 'PageView');
	</script>
	<noscript>
	 <img height="1" width="1" 
	src="https://www.facebook.com/tr?id=433933810863059&ev=PageView
	&noscript=1"/>
	</noscript>
	<!-- End Facebook Pixel Code -->
</head>
<div class= "container-fluid height" id="songs">
	<% if admin_signed_in? %>
		<div class="row newsong">
			<div class="background">
				<b><%= link_to 'Add New Song', new_song_path %></b>
			</div>
		</div>
	<% end %>
		<table>
			<thead>
				<tr>
					<th class="col-xs-12" colspan="4"><h3>Sample Music</h3></th>
				</tr>
			  <tr>
			    <th class="smallcol">Title</th>
			    <th class="smallcol hide410">Artist</th> 
			    <th class="smallcol mobilehide">Genre</th>
			    <th class="widecol hide410"></th>
			    <% if admin_signed_in? %>
        		<th class="smallcol"></th>
      		<% end %>
		  	</tr>
		  </thead>
		  <tbody>
					
					 <% @songs.where( play: true ).each do |song| %>
					  <tr class="hover">
							<td><%= song.title%></td>
							<td class="hide410"><%= song.artist%></td> 
							<td class="mobilehide"><%= song.genre%></td>
							<td class="widecol">
								<audio controls preload="none" controlsList="nodownload"  height="20px"> 
								   <source src="<%= song.file%>" type="audio/mpeg">
								</audio>

							</td>
							<% if admin_signed_in? %>
          			<td>
            			<%= link_to 'Edit', edit_song_path(song) %>
            			<div class="vertical"></div>
            			<%= link_to 'Delete', song, :method => :delete, :confirm => "Are you sure?" %>
       		 			</td>
      				<% end %>
						</tr>
						
						<% end %>
						
			</tbody>
		</table>
	<br><br><br>
	<div class="row">
		<table id="listsongs" scrolling="yes">
				<thead>
					<tr>
						<th colspan="4"><h4>Song list for String Quartet (Two violins, viola and cello)</h4></th>
					</tr>
					<tr>
						<th colspan="4"><h5> Please do not hesitate to request songs that are not on this list.  We will personally arrange any request.</h5></th>
					</tr>
				  <tr>
				    <th>Title</th>
				    <th>Artist/Composer</th> 
				    <% if admin_signed_in? %>
          		<th></th>
      			<% end %>
			  	</tr>
			  </thead>
			  <tbody>
						
						 <% @songs.where( genre: [nil, true] ).each do |song| %>
						  <tr>
								<td><%= song.title%></td>
								<td><%= song.artist%></td> 
								<% if admin_signed_in? %>
	          			<td>
	            			<%= link_to 'Edit', edit_song_path(song) %>
	            			<div class="vertical"></div>
	            			<%= link_to 'Delete', song, :method => :delete, :confirm => "Are you sure?" %>
	       		 			</td>
      					<% end %>
							</tr>	
							<% end %>
					
				</tbody>
			</table>
		</div>
</div>

app/views/songs/new.html.erb
<div class="container-fluid editpage height">
	<div class="background">
		<div class="row">
			<h3>New Song</h3>
		</div>
		<div class="row">
			<%= render 'form', song: @song %>
		</div>
		<div class="row">
			<div class="links">
				<%= link_to 'Back', songs_path %>
			</div>
		</div>
	</div>
</div>

app/views/songs/show.html.erb
<div class="container-fluid editpage height">
  <div class="background">
      <div class="row">
        <p>
          <strong>Title:</strong>
          <%= @song.title %>
        </p>
      </div>
      <div class="row">
        <p>
          <strong>Artist:</strong>
          <%= @song.artist %>
        </p>
      </div>
      <div class="row">
        <p>
          <strong>Genre:</strong>
          <%= @song.genre %>
        </p>
      </div>
      <div class="row">
        <p>
          <strong>File:</strong>
          <%= @song.file %>
        </p>
      </div>
      <div class="row">
        <p>
          <strong>Play:</strong>
          <%= @song.play %>
        </p>
      </div>
      <div class="row links">
        <%= link_to 'Edit', edit_song_path(@song) %> |
        <%= link_to 'Back', songs_path %>
      </div>
    </div>
  </div>