config/routes.rb
Rails.application.routes.draw do

  
  
  get 'contacts/index'

  resources :concerts
  devise_for :admins

  get 'BookingVE', to: 'home#BookingVE', as: 'BookingVE'

  
  get 'admin', to: 'admin#index'
  get 'home', to: 'home#index'
  get 'privacy', to: 'privacy#index'
  get 'reviews', to: 'review#index'
  get 'songs', to: 'songs#index'
  get 'venues', to: 'venues#index'
  get 'emails', to: 'home#index'
  get 'media', to: 'uploads#index'
  # get 'about', to: 'abouts#index'
  get 'contact', to: 'contacts#index'
  resources :contact, only: [:index, :new, :create]

#calendar
# get '/redirect', to: 'example#redirect', as: 'redirect'
# get '/callback', to: 'example#callback', as: 'callback'
  get 'event/:date/:location/:type/:length/:contact_id/:fname/:lname/:email/:phone/:message', to: 'events#new', as: 'new_event_path'

  # get 'new/:amount/:eventdate/:eventlocation/:deposit/:description/:fname/:lname', to: 'charges#new', as: 'new_charge_path'
  namespace :stripe do
    resources :charges, only: :create
  end  
  
  resources :musicians

  resources :events
  resources :customers
  resources :emails

  resources :abouts
  resources :venues
  # resources :uploads
  resources :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/concert.rb
class Concert< ActiveRecord::Base
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  define_model_callbacks :deliver
  include MailForm::Delivery

  # append :remote_ip, :user_agent, :session
  
  attribute :fname, :validate => true
  attribute :lname
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone
  attribute :eventdate, :validate => true
  attribute :eventlocation
  attribute :type
  attribute :heardby
  attribute :length
  attribute :message, :validate => true
  attribute :nickname, :captcha  => true
  attribute :customer_id
  attribute :event_id

  def headers
    {
      :subject => "New Message - Velveteen Ensemble",
      :to => "marcel@velveteenensemble.com", 
      :from =>  %("#{fname}" <#{email}>)
    }
  end
end

app/models/email.rb
class Email < ApplicationRecord
	attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :nickname, :captcha  => true

end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
	 mount_uploader :name, ImageUploader
end

app/models/venue.rb
class Venue < ApplicationRecord

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
  end

  # GET /concerts/1/edit
  def edit
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
      unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
    unless admin_signed_in? 
      flash[:notice] = "You don't have access to that page!"
      redirect_to root_path
      return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:title, :subtitle, :about, :comp1name, :comp1bio, :comp1pic, :comp2name, :comp2bio, :comp2pic, :comp3name, :comp3bio, :comp3pic, :comp4name, :comp4bio, :comp4pic)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :concert_title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :concert_subtitle %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about, id: :concert_about %>
  </div>

<hr>

  <div class="field">
    <%= form.label :composer_1, class: :leftm  %>
    <%= form.text_field :comp1name, id: :concert_comp1name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :comp1bio, id: :concert_comp1bio %>
  </div>

 <!--  <div class="field">
    <#%= form.file_field :comp1pic %>
    
  </div> -->

<hr>

  <div class="field">
    <%= form.label :composer_2, class: :leftm  %>
    <%= form.text_field :comp2name, id: :concert_comp2name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :comp2bio, id: :concert_comp2bio %>
  </div>

<!--   <div class="field">
    <#%= form.file_field :comp2pic %>
  </div> -->

<hr>

  <div class="field">
    <%= form.label :composer_3, class: :leftm  %>
    <%= form.text_field :comp3name, id: :concert_comp3name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :comp3bio, id: :concert_comp3bio %>
  </div>

 <!--  <div class="field">
    <#%= form.file_field :comp3pic %>

  </div> -->

<hr>

  <div class="field">
    <%= form.label :composer_4, class: :leftm %>
    <%= form.text_field :comp4name, id: :concert_comp4name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :comp4bio, id: :concert_comp4bio %>
  </div>

 <!--  <div class="field">
    <#%= form.file_field :pic %>
  </div> -->

<hr>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<div class="container-fluid editpage height">
	<div class="background" id="newconcert">
		<div class="row">
			<h3>Editing Concert</h3>
		</div>
		<div class="row">
			<%= render 'form', concert: @concert %>
		</div>
		<div class="row">
			<div class="links">
				<%= link_to 'Show', @concert %> |
				<%= link_to 'Back', root_path %>
			</div>
		</div>
	</div>
</div>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>About</th>
      <th>Comp1name</th>
      <th>Comp1bio</th>
      <th>Comp1pic</th>
      <th>Comp2name</th>
      <th>Comp2bio</th>
      <th>Comp2pic</th>
      <th>Comp3name</th>
      <th>Comp3bio</th>
      <th>Comp3pic</th>
      <th>Comp4name</th>
      <th>Comp4bio</th>
      <th>Comp4pic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.title %></td>
        <td><%= concert.subtitle %></td>
        <td><%= concert.about %></td>
        <td><%= concert.comp1name %></td>
        <td><%= concert.comp1bio %></td>
        <td><%= concert.comp1pic %></td>
        <td><%= concert.comp2name %></td>
        <td><%= concert.comp2bio %></td>
        <td><%= concert.comp2pic %></td>
        <td><%= concert.comp3name %></td>
        <td><%= concert.comp3bio %></td>
        <td><%= concert.comp3pic %></td>
        <td><%= concert.comp4name %></td>
        <td><%= concert.comp4bio %></td>
        <td><%= concert.comp4pic %></td>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path %>

app/views/concerts/new.html.erb
<div class="container-fluid editpage height">
	<div class="background" id="newconcert">
		<div class="row">
			<h3>New Concert</h3>
		</div>
		<div class="row">
			<%= render 'form', concert: @concert %>
		</div>
		<div class="row">
			<div class="links">
				<%= link_to 'Back', root_path %>
			</div>
		</div>
	</div>
</div>

app/views/concerts/show.html.erb
<head>
  <title>Velveteen Ensemble Concert Page</title>
  <!-- Facebook Pixel Code -->
  <script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window,document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
   fbq('init', '433933810863059'); 
  fbq('track', 'PageView');
  </script>
  <noscript>
   <img height="1" width="1" 
  src="https://www.facebook.com/tr?id=433933810863059&ev=PageView
  &noscript=1"/>
  </noscript>
  <!-- End Facebook Pixel Code -->
</head>
<div id="concert" class="container-fluid height">
  <div class="col-md-12 background">
  <h2><%= @concert.title %></h2>
  <img id="logo" src="https://d3ffc7oj6uo4uj.cloudfront.net/whlogolines.png" alt="Whlogolines">
<h4><strong><%= @concert.subtitle %></strong></h4>
<br>
<p><%= @concert.about %></p>
<br><br>
<div class="row">
  <div class="col-sm-4 col-md-4">
    <%=image_tag image_url("https://d3ffc7oj6uo4uj.cloudfront.net/bartok.jpeg")%>
  </div>
  <div class="col-sm-8 col-md-8">
    <div class="row pad">
      <p><Strong><%= @concert.comp1name %></Strong></p>
    </div>
    <div class="row">
      <p><%= @concert.comp1bio %></p>
    </div>
    
  </div>
</div>

<hr>

<div class="row">
  <div class="col-sm-4 col-md-4">
    <%=image_tag image_url("https://d3ffc7oj6uo4uj.cloudfront.net/ponce.jpeg")%>
  </div>
  <div class="col-sm-8 col-md-8">
    <div class="row pad">
      <p><Strong><%= @concert.comp2name %></Strong></p>
    </div>
    <div class="row">
      <p><%= @concert.comp2bio %></p>
    </div>
    
  </div>
  
</div>

<hr>

<div class="row">
  <div class="col-sm-4 col-md-4">
    <%=image_tag image_url("https://d3ffc7oj6uo4uj.cloudfront.net/rodrigo.jpeg")%>
  </div>
  <div class="col-sm-8 col-md-8">
    <div class="row pad">
      <p><Strong><%= @concert.comp3name %></Strong></p>
    </div>
    <div class="row">
      <p><%= @concert.comp3bio %></p>
    </div>
    
  </div>
</div>

<hr>

<div class="row">
  <div class="col-sm-4 col-md-4">
    <%=image_tag image_url("https://d3ffc7oj6uo4uj.cloudfront.net/boccherini.jpeg")%>
  </div>
  <div class="col-sm-8 col-md-8">
    <div class="row pad">
      <p><Strong><%= @concert.comp4name %></Strong></p>
    </div>
    <div class="row">
      <p><%= @concert.comp4bio %></p>
    </div>
    
  </div>
  
</div>
<br><br>
  <% if admin_signed_in? %>
<%= link_to 'Edit', edit_concert_path(@concert) %> |
<% end %>
<%= link_to 'Back', root_path %>
</div>
</div>